In [6]:
#numpy.ipynb

import numpy as np

list1 = [1, 2, 3, 4]

print(f'list1[{0}]: {list1[0]}')

a = np.array(list1)
print(f'a.shape: {a.shape}')
print(f'a[0]: {a[0]}')

# 2차원 배열 생성
b = np.array([[1, 2, 3], [4, 5, 6]])
print(f'b.shape: {b.shape}')
print(f'b[0, 1]: {b[0, 1]}')

list1[0]: 1
a.shape: (4,)
a[0]: 1
b.shape: (2, 3)
b[0, 1]: 2


In [15]:
# 넘파이 배열을 생성하는 함수
a = np.zeros(2, dtype=int)
a

array([0, 0])

In [16]:
b = np.zeros((2, 2), dtype=int)
b

array([[0, 0],
       [0, 0]])

In [18]:
c = np.ones((2, 3), dtype=int)
c

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
d = np.full((2, 3), 100)
d

array([[100, 100, 100],
       [100, 100, 100]])

In [20]:
e = np.eye(3, dtype=int) # identity()와 같음
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
# 기본 파이썬 range 함수
for i in range(1, 6):
    print(i)

1
2
3
4
5


In [22]:
# range()와 비슷한 함수: arange()
for i in np.arange(1, 6):
    print(i)

1
2
3
4
5


In [26]:
print(type([1, 2]))

a = np.array([1, 2], dtype=np.float64) # 8byte
print(a.dtype)

b = a.astype(np.int8)
print(b.dtype)

<class 'list'>
float64
int8


In [28]:
# ndarray 속성
# [
#   [0, 1, 2],
#   [3, 4, 5]
# ]
arr = np.array([[0, 1, 2], [3, 4, 5]])
print(f'type(arr): {type(arr)}')
print(f'arr.ndim: {arr.ndim}')
print(f'arr.dtype: {arr.dtype}')
print(f'arr.itemsize: {arr.itemsize}')
print(f'arr.size: {arr.size}')
print(f'arr.nbytes: {arr.nbytes}')
print(f'arr.T:\n {arr.T}')
print(f'arr.shape: {arr.shape}')

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


In [48]:
a = np.arange(8) # 0부터 7까지 배열로 저장
print(f'a: \n{a}')
print(f'shape:\n{a.shape}')
a.shape = (2, 2, 2) # 머신러닝에서 차원의 축소를 실행할 때 사용
# a = a.reshape(2, 4)
print(f'shape:\n{a.shape}')
print(f'a:\n{a}')
# flatten => 평평하게 하다
print(f'flatten:\n{a.flatten()}')

# resize()로 함수 모양 변경하기
a.resize(4,2)
print(f'resize:\n{a}')

# transpose()를 이용하여 행과 열을 교차하여 표현하기
b = a.transpose()
print(f'b:\n{b}')


a: 
[0 1 2 3 4 5 6 7]
shape:
(8,)
shape:
(2, 2, 2)
a:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
flatten:
[0 1 2 3 4 5 6 7]
resize:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
b:
[[0 2 4 6]
 [1 3 5 7]]


In [49]:
# p211 확인문제 1
# 0부터 9까지의 1차원 배열 생성
# a = range(10)
a = np.arange(10)
# a.shape = (2, 5)
a = a.reshape(2, 5)
# b = a.T
b = a.transpose()
print(f'a:\n{a}')
print(f'b:\n{b}')

a:
[[0 1 2 3 4]
 [5 6 7 8 9]]
b:
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [51]:
# p211 확인문제 2
list1 = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]
a = np.array(list1)
print(a[1:3, :2])

[[4 5]
 [7 8]]


In [59]:
import csv
box_office = []
with open('boxoffice.csv', encoding='utf-8') as f:
    reader = csv.reader(f)
    for row in reader:
        box_office.append(row)

bo = np.array(box_office)
bo[bo[:, 2] == '전체관람가']

array([['그대들은 어떻게 살 것인가', '23.10.25', '전체관람가', '1,975,751'],
       ['스노우 폭스: 썰매개가 될 거야!', '23.11.23', '전체관람가', '68,655'],
       ['겨울왕국', '23.11.30', '전체관람가', '10,324,794'],
       ['극장판 우당탕탕 은하안전단: 진정한 용기!', '23.11.30', '전체관람가', '22,117'],
       ['겨울왕국 2', '23.11.30', '전체관람가', '13,764,388'],
       ['이빨요정 비올레타: 요정나라로 돌아갈래!', '23.11.18', '전체관람가', '53,554']],
      dtype='<U24')

In [71]:
# Numpy의 Broadcasting
list1 = [1, 2, 3, 4, 5, 6]
a = np.array(list1)
print(a)
b = a * 10
print(b)

list2 = [9, 8, 7, 6, 5, 4]
b = np.array(list2)
c = a + b
print(c)

d = list1 + list2
print(d)


[1 2 3 4 5 6]
[10 20 30 40 50 60]
[10 10 10 10 10 10]
[1, 2, 3, 4, 5, 6, 9, 8, 7, 6, 5, 4]


In [76]:
a = np.array([3, 9, 1, 6, 2, 8])
print(f'원본: {a}')

# print(f'정렬 후: {np.sort(a)}') # 배열을 정렬해서, 새로운 배열 객체 반환
# a.sort()
# print(f'정렬 후: {a}')  # 배열을 정렬(원본을 정렬)

# np.argsort(배열)
print(f'정렬 후: {np.sort(a)}')
print(f'정렬하기 전 인덱스: {np.argsort(a)}')


원본: [3 9 1 6 2 8]
정렬 후: [1 2 3 6 8 9]
정렬하기 전 인덱스: [2 4 0 3 5 1]


In [77]:
a = np.array([1, 2, 3])
b = np.array([4])
c = a + b
print(c)

[5 6 7]
